# Generated by Django 4.1.7 on 2023-03-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kind_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opening', models.DateField()),
                ('date_closing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Software_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cell_number', models.CharField(max_length=50)),
                ('fk_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.country')),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.user_rol')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField()),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.software_product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('fk_developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.user')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.software_product')),
            ],
        ),
        migrations.AddField(
            model_name='software_product',
            name='fk_developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.user'),
        ),
        migrations.AddField(
            model_name='software_product',
            name='fk_kind_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.kind_product'),
        ),
        migrations.AddField(
            model_name='software_product',
            name='fk_license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.license'),
        ),
        migrations.AddField(
            model_name='software_product',
            name='fk_resources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.resources'),
        ),
        migrations.AddField(
            model_name='software_product',
            name='fk_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.technology'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.bank')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.user')),
                ('fk_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.stock')),
                ('fk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.store')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_date_record', models.DateField()),
                ('fk_date_sale', models.DateField()),
                ('fk_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAO_db.sale')),
            ],
        ),
    ]
