# Generated by Django 4.1.7 on 2023-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_rol', models.PositiveIntegerField()),
                ('fk_country', models.PositiveIntegerField()),
                ('fk_history', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cell_number', models.CharField(max_length=50)),
            ],
        ),
    ]
