# Generated by Django 4.1.7 on 2023-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_date_record', models.DateField()),
                ('fk_date_sale', models.DateField()),
                ('fk_client', models.PositiveIntegerField()),
                ('fk_developer', models.PositiveIntegerField()),
                ('fk_sale', models.PositiveIntegerField()),
                ('fk_bank', models.PositiveIntegerField()),
                ('fk_history', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
