# Generated by Django 4.1.7 on 2023-03-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_country_history_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fk_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fk_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.history'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fk_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_rol'),
        ),
    ]
